// lib/mockData.ts
import { Sale } from '@/types';

export const mockSales: Sale[] = [
  {
    id: '1',
    orderNumber: 1001,
    date: '2025-10-25T10:30:00Z',
    customerName: 'Juan Pérez',
    grossRevenue: 25000,
    tiendaNubeFee: 750, // 3% de Tienda Nube
    paymentFee: 1250, // 5% tarjeta crédito
    shippingCost: 2000,
    productCost: 12000,
    advertisingCost: 3000,
    netRevenue: 6000,
    netMargin: 24,
    paymentMethod: 'Tarjeta de Crédito 3 cuotas',
    shippingMethod: 'Correo Argentino',
    products: [
      {
        id: 'p1',
        name: 'Remera Premium',
        sku: 'REM-001',
        quantity: 2,
        price: 12500,
        cost: 6000,
        total: 25000,
      },
    ],
    currency: 'ARS',
    status: 'paid',
  },
  {
    id: '2',
    orderNumber: 1002,
    date: '2025-10-26T14:20:00Z',
    customerName: 'María González',
    grossRevenue: 18000,
    tiendaNubeFee: 540,
    paymentFee: 0, // Transferencia sin comisión
    shippingCost: 1800,
    productCost: 8000,
    advertisingCost: 2500,
    netRevenue: 5160,
    netMargin: 28.67,
    paymentMethod: 'Transferencia Bancaria',
    shippingMethod: 'Andreani',
    products: [
      {
        id: 'p2',
        name: 'Pantalón Jogger',
        sku: 'PAN-002',
        quantity: 1,
        price: 18000,
        cost: 8000,
        total: 18000,
      },
    ],
    currency: 'ARS',
    status: 'paid',
  },
  {
    id: '3',
    orderNumber: 1003,
    date: '2025-10-27T09:15:00Z',
    customerName: 'Carlos Rodríguez',
    grossRevenue: 42000,
    tiendaNubeFee: 1260,
    paymentFee: 2100,
    shippingCost: 2500,
    productCost: 20000,
    advertisingCost: 4000,
    netRevenue: 12140,
    netMargin: 28.9,
    paymentMethod: 'Tarjeta de Débito',
    shippingMethod: 'Retiro en sucursal',
    products: [
      {
        id: 'p3',
        name: 'Campera de Invierno',
        sku: 'CAM-001',
        quantity: 1,
        price: 42000,
        cost: 20000,
        total: 42000,
      },
    ],
    currency: 'ARS',
    status: 'paid',
  },
  {
    id: '4',
    orderNumber: 1004,
    date: '2025-10-28T16:45:00Z',
    customerName: 'Ana Martínez',
    grossRevenue: 15000,
    tiendaNubeFee: 450,
    paymentFee: 750,
    shippingCost: 1500,
    productCost: 7000,
    advertisingCost: 2000,
    netRevenue: 3300,
    netMargin: 22,
    paymentMethod: 'Mercado Pago',
    shippingMethod: 'OCA',
    products: [
      {
        id: 'p4',
        name: 'Zapatillas Deportivas',
        sku: 'ZAP-001',
        quantity: 1,
        price: 15000,
        cost: 7000,
        total: 15000,
      },
    ],
    currency: 'ARS',
    status: 'paid',
  },
  {
    id: '5',
    orderNumber: 1005,
    date: '2025-10-29T11:00:00Z',
    customerName: 'Luis Fernández',
    grossRevenue: 32000,
    tiendaNubeFee: 960,
    paymentFee: 1600,
    shippingCost: 2200,
    productCost: 15000,
    advertisingCost: 3500,
    netRevenue: 8740,
    netMargin: 27.31,
    paymentMethod: 'Tarjeta de Crédito 6 cuotas',
    shippingMethod: 'Correo Argentino',
    products: [
      {
        id: 'p5',
        name: 'Buzo con Capucha',
        sku: 'BUZ-001',
        quantity: 2,
        price: 16000,
        cost: 7500,
        total: 32000,
      },
    ],
    currency: 'ARS',
    status: 'paid',
  },
];

// Configuración por defecto de costos
export const defaultCostSettings = {
  tiendaNubeFeePercentage: 3,
  paymentMethods: {
    'credit_card': {
      name: 'Tarjeta de Crédito',
      feePercentage: 5,
      fixedFee: 0,
    },
    'debit_card': {
      name: 'Tarjeta de Débito',
      feePercentage: 3,
      fixedFee: 0,
    },
    'transfer': {
      name: 'Transferencia',
      feePercentage: 0,
      fixedFee: 0,
    },
    'mercadopago': {
      name: 'Mercado Pago',
      feePercentage: 4.99,
      fixedFee: 0,
    },
  },
};
